config/routes.rb
Rails.application.routes.draw do

  # 記事/キーワード機能
  namespace :writers do
    get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
    get 'articles/keyword', to: 'articles#keyword', as: 'keyword'
    patch 'articles/:id/apply', to: 'articles#apply', as: 'apply_article'
    get 'articles/:id/heading/edit', to: 'articles#edit_heading', as: 'edit_heading'
    patch 'articles/:id/heading', to: 'articles#update_heading', as: 'heading'
    patch 'articles/:id/heading/apply', to: 'articles#apply_heading', as: 'apply_heading'
    resources :articles, except: [:destroy, :new, :edit]
  end

  namespace :admins do
    get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
    patch 'articles/:id/approve', to: 'articles#approve', as: 'approve_article'
    get 'articles/:id/heading/edit', to: 'articles#edit_heading', as: 'edit_heading'
    patch 'articles/:id/heading', to: 'articles#update_heading', as: 'heading'
    patch 'articles/:id/heading/approve', to: 'articles#approve_heading', as: 'approve_heading'
    resources :articles, except: [:create, :new, :edit]
  end

  # 認証機能
  devise_for :writers, controllers: { sessions: 'writers/sessions'}, skip: [:registrations]
  devise_scope :writer do
  	get 'writers/sign_up', to:'writers/registrations#new', as: 'new_writer_registration'
  	get 'writers/edit', to:'writers/registrations#edit', as: 'edit_writer_registration'
    patch 'writers', to:'writers/registrations#update', as: 'writer_registration'
    put 'writers', to:'writers/registrations#update', as: nil
    post 'writers', to:'writers/registrations#create', as: nil
  	post 'writers/sign_up/confirm', to: 'writers/registrations#confirm', as: 'confirm_writer_registration'
  	post 'writers/sign_up', to: 'writers/registrations#back', as: 'back_writer_registration'
  end

  root to: 'writers/writers#show'

  devise_for :admins, controllers: {sessions: 'admins/sessions'}, skip: [:registrations]
  namespace :admins do
  	get '', to: 'admins#top'
  end

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :writer, optional: true
  has_many :headings, dependent: :destroy
  accepts_nested_attributes_for :headings, allow_destroy: true
  has_one :feedback, dependent: :destroy

  enum status: {edit_heading: 0, apply_heading: 1, edit: 2, apply: 3, complete: 4}
  validates :title, length: { maximum: 35, message: 'は35文字以内にしてください' }


  with_options on: :apply_heading do
    validates :title, presence: { message: "を埋めてください"}
    validates :reference_1, presence: { message: "を埋めてください"}
    validates :reference_2, presence: { message: "を埋めてください"}
    validates :reference_3, presence: { message: "を埋めてください"}
    validates :headings, presence: { message: "が1つもありません"}
    validate :heading_has_title?
    validate :subheading_has_title?
    validate :subsubheading_has_title?
  end

  with_options on: :apply do
    validate :heading_has_body?
    validate :subheading_has_body?
    validate :subsubheading_has_body?
  end

  def heading_has_title?
    self.headings.each do |heading|
      if heading.title.blank?
        return errors.add(:heading, "のtitleを埋めてください")
      end
    end
  end

  def subheading_has_title?
    self.headings.each do |heading|
      heading.subheadings.each do |subheading|
        if subheading.title.blank?
          return errors.add(:subheading, "のtitleを埋めてください")
        end
      end
    end
  end

  def subsubheading_has_title?
    self.headings.each do |heading|
      heading.subheadings.each do |subheading|
        subheading.subsubheadings.each do |subsubheading|
          if subsubheading.title.blank?
            return errors.add(:subsubheading, "のtitleを埋めてください")
          end
        end
      end
    end
  end

  def heading_has_body?
    self.headings.each do |heading|
      if heading.body.blank?
        return errors.add(:heading, "のbodyを埋めてください")
      end
    end
  end

  def subheading_has_body?
    self.headings.each do |heading|
      heading.subheadings.each do |subheading|
        if subheading.body.blank?
          return errors.add(:subheading, "のbodyを埋めてください")
        end
      end
    end
  end

  def subsubheading_has_body?
    self.headings.each do |heading|
      heading.subheadings.each do |subheading|
        subheading.subsubheadings.each do |subsubheading|
          if subsubheading.body.blank?
            return errors.add(:subsubheading, "のbodyを埋めてください")
          end
        end
      end
    end
  end

end

app/models/writer.rb
class Writer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles

  enum sex: { 男: 0, 女: 1, その他: 2}, _suffix: true
  # enum表記方法は、上記と下記どちらでも同じ
  enum occupation: [:会社員, :フリーター, :専業主婦または主夫, :その他], _suffix: true
  enum experience_year: [:未経験, :一年未満, :一年以上]
  enum status: [:トライアル, :契約済み, :アカウント停止]

  validates :last_name, presence: { message: "苗字を入力してください" }
  validates :first_name, presence: { message: "名前を入力してください" }
  validates :last_name_kana, presence: { message: "カナ苗字を入力してください" }, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'は全角カタカナで入力して下さい'}
  validates :first_name_kana, presence: { message: "カナ名前を入力してください" }, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'は全角カタカナで入力して下さい'}
  validates :sex, presence: { message: "性別を選択してください" }
  validates :birthdate, presence: { message: "生年月日を入力してください" }
  validates :occupation, presence: { message: "職業を選択してください" }
  validates :experience_year, presence: { message: "ライター経験年数を選択してください" }
  validates :password, format: { with: /\A[a-zA-Z0-9]+\z/, message: 'は半角英数字で入力して下さい'}
end

app/controllers/admins/articles_controller.rb
class Admins::ArticlesController < ApplicationController
  def index
  end

  def show
  end

  def edit_heading
  end

  def edit
  end
end

app/controllers/writers/articles_controller.rb
class Writers::ArticlesController < ApplicationController
  before_action :authenticate_writer!

  #def keyword
  #end

  def create
    @article = Article.new(article_params)
    @article.writer_id = current_writer.id
    @article.keyword_1 = '髪の毛' #変更予定, spreadsheetから引っ張ってくる
    @article.keyword_2 = Time.new.min #変更予定, spreadsheetから引っ張ってくる
    @article.unit_price = current_writer.unit_price
    @article.save
    redirect_to writers_articles_path
  end

  def index
    @article = Article.new #削除予定
    @articles = Article.where(writer_id: current_writer.id)
    @q = Article.ransack(params[:q])
    if params[:q].present?
      @articles = @q.result(distinct: true).where(writer_id: current_writer.id)
      render :index
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit_heading
    @article = Article.find(params[:id])
    unless @article.status == 'edit_heading'
      flash.now[:danger] = 'この記事の見出しは編集できません'
      render 'show'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to writers_article_path(@article)
    else
      render 'edit_heading'
    end
  end

  def apply_heading
    @article = Article.find(params[:id])
    if @article.valid?(:apply_heading)
      @article.status = 1
      @article.save
      redirect_to writers_article_path(@article), notice: "見出しを申請しました"
    else
      render 'show'
    end
  end

  def edit
    @article = Article.find(params[:id])
    unless @article.status == 'edit'
      flash.now[:danger] = 'この記事の本文は編集できません'
      render 'show'
    end
  end

  def apply
    @article = Article.find(params[:id])
    if @article.valid? (:apply)
      @article.status = 3
      @article.save
      redirect_to writers_article_path(@article), notice: "記事を申請しました"
    else
      render 'show'
    end
  end

  private
  def article_params
    params.require(:article).permit(:writer_id, :keyword_1, :keyword_2, :keyword_3, :status, :title, :reference_1, :reference_2, :reference_3, :reference_4, :reference_5, :unit_price,
      headings_attributes: [:id, :title, :body, :_destroy,
        subheadings_attributes: [:id, :title, :body, :_destroy,
          subsubheadings_attributes: [:id, :title, :body, :_destroy]
        ]])
  end
end

app/controllers/writers/confirmations_controller.rb
# frozen_string_literal: true

class Writers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/writers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Writers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/writers/passwords_controller.rb
# frozen_string_literal: true

class Writers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/writers/registrations_controller.rb
# frozen_string_literal: true

class Writers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def confirm
    @writer = Writer.new(writer_params)
    return if @writer.valid?
    render :new
  end

  def back
    @writer = Writer.new(writer_params)
    render :new
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private
  def writer_params
    params.require(:writer).permit(:email, :password, :password_confirmation, :last_name, :first_name, :last_name_kana, :first_name_kana, :sex, :birthdate, :occupation, :experience_year, :status, :unit_price)
  end
end

app/controllers/writers/sessions_controller.rb
# frozen_string_literal: true

class Writers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   #protected
   #def customized_flash
   #end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/writers/unlocks_controller.rb
# frozen_string_literal: true

class Writers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/writers/writers_controller.rb
class Writers::WritersController < ApplicationController
  before_action :authenticate_writer!
  def show
  	@writer = current_writer
  end
end

app/helpers/admins/articles_helper.rb
module Admins::ArticlesHelper
end

app/helpers/writers/articles_helper.rb
module Writers::ArticlesHelper
end

app/helpers/writers/writers_helper.rb
module Writers::WritersHelper
end

app/views/writers/articles/_heading_fields.html.erb
<div class="nested-fields">
	<%= f.label :title, "大見出し" %>
	<%= f.text_field :title %>
	<%= link_to_remove_association "remove heading", f %>
	<div class="subheadings">
		<%= f.fields_for :subheadings do |subheading| %>
		  <%= render "subheading_fields", f: subheading %>
	  <% end %>
		<div class="links">
			<%= link_to_add_association "add subheading", f, :subheadings %>
		</div>
  </div>
</div>

app/views/writers/articles/_subheading_fields.html.erb
<div class="nested-fields">
	<%= f.label :title, "中見出し" %>
	<%= f.text_field :title %>
	<%= link_to_remove_association "remove subheading", f %>
	<div class="subsubheadings">
		<%= f.fields_for :subsubheadings do |subsubheading| %>
		  <%= render "subsubheading_fields", f: subsubheading %>
	  <% end %>
		<div class="links">
			<%= link_to_add_association "add subsubheading", f, :subsubheadings %>
		</div>
  </div>
</div>

app/views/writers/articles/_subsubheading_fields.html.erb
<div class="nested-fields">
	<%= f.label :title, "小見出し" %>
	<%= f.text_field :title %>
	<%= link_to_remove_association "remove subsubheading", f %>
</div>

app/views/writers/articles/edit.html.erb
<h1>記事本文編集ページ</h1>
<p><%= current_writer.last_name %> <%= current_writer.first_name %>様</p>
<%= @article.keyword_1 %>
- <%= @article.keyword_2 %>
<% if @article.keyword_3.present? %>
- <%= @article.keyword_3 %>
<% end %>


<br>
参考URL:
<br>1- <%= link_to "#{@article.reference_1}", @article.reference_1, target: "_blank" %>
<br>2- <%= link_to "#{@article.reference_2}", @article.reference_2, target: "_blank" %>
<br>3- <%= link_to "#{@article.reference_3}", @article.reference_3, target: "_blank" %>
<br>4- <%= link_to "#{@article.reference_4}", @article.reference_4, target: "_blank" %>
<br>5- <%= link_to "#{@article.reference_5}", @article.reference_5, target: "_blank" %>
<br>


<div>
	<%= form_for(@article, url: writers_article_path(@article)) do |f| %>
		<h3>タイトル: <%= @article.title %></h3>

<%= f.fields_for :headings do |f| %>
<h4>- 大見出し：<%= f.object.title %></h4>
<div><%= f.text_area :body, style: "width: 80%; height: 100px; margin-bottom: 20px;" %></div>

<%= f.fields_for :subheadings do |f| %>
<h5>------ 中見出し：<%= f.object.title %></h5>
<%= f.text_area :body, style: "width: 80%; height: 100px; margin-bottom: 20px;" %>

<%= f.fields_for :subsubheadings do |f| %>
<h6>------------ 小見出し：<%= f.object.title %></h6>
<%= f.text_area :body, style: "width: 80%; height: 100px; margin-bottom: 20px;" %>

<% end %>
<% end %>
<% end %>


	<%= f.submit "保存", class: "btn btn-success" %>
	<%= link_to "内容を破棄して戻る", writers_article_path(@article), class: "btn btn-default" %>


	<% end %>
</div>

app/views/writers/articles/edit_heading.html.erb
<h1>見出し編集ページ</h1>
<p><%= current_writer.last_name %> <%= current_writer.first_name %>様</p>
<%= @article.keyword_1 %>
- <%= @article.keyword_2 %>
<% if @article.keyword_3.present? %>
- <%= @article.keyword_3 %>
<% end %>

<%= form_for(@article, url: writers_article_path(@article)) do |f| %>
<br>
参考URL:
<br>
<%= f.label :reference_1, "- 1:" %>
<%= f.url_field :reference_1, placeholder: "入力必須項目" %>
<br>
<%= f.label :reference_2, "- 2:" %>
<%= f.url_field :reference_2, placeholder: "入力必須項目" %>
<br>
<%= f.label :reference_3, "- 3:" %>
<%= f.url_field :reference_3, placeholder: "入力必須項目" %>
<br>
<%= f.label :reference_4, "- 4:" %>
<%= f.url_field :reference_4 %>
<br>
<%= f.label :reference_5, "- 5:" %>
<%= f.url_field :reference_5 %>
<br>
<br>
<%= f.label :title, "タイトル:" %>
<%= f.text_field :title %>

<br>

<div id="headings">
	<%= f.fields_for :headings do |heading| %>
		<%= render "heading_fields", f: heading %>
	<% end %>

	<div id="links">
		<%= link_to_add_association "add heading", f, :headings %>
	</div>



<%= f.submit "保存", class: "btn btn-success" %>
<%= link_to "内容を破棄して戻る", writers_article_path(@article), class: "btn btn-default" %>
<% end %>

app/views/writers/articles/index.html.erb
<h1>記事一覧</h1>
<p>ライターID：<%= current_writer.id %></p>
<p><%= current_writer.last_name %> <%= current_writer.first_name %>様</p>


<%= form_for(@article, url: writers_articles_path) do |f| %>
<%= f.text_field :keyword_3, placeholder: "keyword_3" %>
<%= f.submit "新規記事作成" %>
<% end %>

<%= search_form_for @q, url: writers_articles_path do |f| %>
<%= f.select :status_eq, Article.statuses.map {|k, v| [Article.statuses_i18n[k], v]}, include_blank: '選択してください' %>
<%= f.submit "さがす" %>
  <% end %>

<table class="table">
  <thead>
  	<tr>
  	  <th>ID</th>
  	  <th>ライターID</th>
	  	<th>キーワード</th>
	  	<th>ステータス</th>
	  	<th>受注日</th>
	  	<th>更新日</th>
	  	<th></th>
	  </tr>
	</thead>
	<tbody>
		<% @articles.each do |article| %>
		<tr>
			<td><%= article.id %></td>
			<td><%= article.writer_id %></td>
			<td>
				<%= link_to writers_article_path(article) do %>
					<%= article.keyword_1 %>
					- <%= article.keyword_2 %>
			  	<% if article.keyword_3.present? %>
			  	- <%= article.keyword_3 %>
			  	<% end %>
			  <% end %>
			 </td>
			<td><%= article.status_i18n %></td>
			<td><%= l article.created_at, format: :middle %></td>
			<td><%= l article.updated_at, format: :middle %></td>
			<td>
				<% if article.status == 'edit_heading' %>
				<%= link_to "見出しを執筆", writers_edit_heading_path(article), class: "btn btn-primary" %>
				<% elsif article.status == 'edit' %>
				<%= link_to "本文を執筆", writers_edit_article_path(article), class: "btn btn-primary" %>
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/writers/articles/keyword.html.erb
<h1>Writers::Articles#keyword</h1>
<p>Find me in app/views/writers/articles/keyword.html.erb</p>

app/views/writers/articles/show.html.erb
<h1>記事詳細ページ</h1>
<%= link_to "記事一覧ページに戻る", writers_articles_path %>
<p><%= current_writer.last_name %> <%= current_writer.first_name %>様</p>
<%= @article.keyword_1 %>
- <%= @article.keyword_2 %>
<% if @article.keyword_3.present? %>
- <%= @article.keyword_3 %>
<% end %>

<br>
<%= @article.status_i18n %>

<br>
参考URL:
<br>1- <%= link_to "#{@article.reference_1}", @article.reference_1, target: "_blank" %>
<br>2- <%= link_to "#{@article.reference_2}", @article.reference_2, target: "_blank" %>
<br>3- <%= link_to "#{@article.reference_3}", @article.reference_3, target: "_blank" %>
<br>4- <%= link_to "#{@article.reference_4}", @article.reference_4, target: "_blank" %>
<br>5- <%= link_to "#{@article.reference_5}", @article.reference_5, target: "_blank" %>
<br>
タイトル：<%= @article.title %>


<br>
目次：<br>
<% if @article.headings.present? %>
	<% @article.headings.each do |heading| %>
		・<%= heading.title %><br>
		<% heading.subheadings.each do |subheading| %>
		  - <%= subheading.title %><br>
		  <% subheading.subsubheadings.each do |subsubheading| %>
		    - - <%= subsubheading.title %><br>
		  <% end %>
		<% end %>
	<% end %>
	<br>
	<% @article.headings.each do |heading| %>
		大見出し：<%= heading.title %><br>
		<%= heading.body %><br>
		<% heading.subheadings.each do |subheading| %>
		  中見出し：<%= subheading.title %><br>
		  <%= subheading.body %><br>
		  <% subheading.subsubheadings.each do |subsubheading| %>
		    小見出し：<%= subsubheading.title %><br>
		    <%= subsubheading.body %><br>
		  <% end %>
		<% end %>
	<% end %>
<% else %>
	<p>見出しはありません</p>
<% end %>





フィードバック：
<% if @article.feedback.present? %>
  <%= @article.feedback.body %>
<% else %>
  <p>フィードバックはありません</p>
<% end %>

<br>
<% if @article.status == 'edit_heading' %>
	<%= link_to "見出しを執筆", writers_edit_heading_path(@article), class: "btn btn-primary" %>
	<%= link_to "見出しを申請", writers_apply_heading_path(@article), method: :patch, class: "btn btn-success" %>
<% elsif @article.status == 'edit' %>
	<%= link_to "本文を執筆", writers_edit_article_path(@article), class: "btn btn-primary" %>
	<%= link_to "本文を申請", writers_apply_article_path(@article), method: :patch, class: "btn btn-success" %>
<% end %>