config/routes.rb
Rails.application.routes.draw do

  # 記事/キーワード機能
  namespace :writers do
    get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
    get 'articles/keyword', to: 'articles#keyword', as: 'keyword'
    patch 'articles/:id/apply', to: 'articles#apply', as: 'apply_article'
    get 'articles/:id/heading/edit', to: 'articles#edit_heading', as: 'edit_heading'
    patch 'articles/:id/heading', to: 'articles#update_heading', as: 'heading'
    patch 'articles/:id/heading/apply', to: 'articles#apply_heading', as: 'apply_heading'
    resources :articles, except: [:destroy, :new, :edit]
  end

  namespace :admins do
    get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
    patch 'articles/:id/approve', to: 'articles#approve', as: 'approve_article'
    get 'articles/:id/heading/edit', to: 'articles#edit_heading', as: 'edit_heading'
    patch 'articles/:id/heading', to: 'articles#update_heading', as: 'heading'
    patch 'articles/:id/heading/approve', to: 'articles#approve_heading', as: 'approve_heading'
    resources :articles, except: [:create, :new, :edit]
  end

  # 認証機能
  devise_for :writers, controllers: { sessions: 'writers/sessions'}, skip: [:registrations]
  devise_scope :writer do
  	get 'writers/sign_up', to:'writers/registrations#new', as: 'new_writer_registration'
  	get 'writers/edit', to:'writers/registrations#edit', as: 'edit_writer_registration'
    patch 'writers', to:'writers/registrations#update', as: 'writer_registration'
    put 'writers', to:'writers/registrations#update', as: nil
    post 'writers', to:'writers/registrations#create', as: nil
  	post 'writers/sign_up/confirm', to: 'writers/registrations#confirm', as: 'confirm_writer_registration'
  	post 'writers/sign_up', to: 'writers/registrations#back', as: 'back_writer_registration'
  end

  root to: 'writers/writers#show'

  devise_for :admins, controllers: {sessions: 'admins/sessions'}, skip: [:registrations]
  namespace :admins do
  	get '', to: 'admins#top'
  end

end

app/views/layouts/_admins_header.html.erb
    <% if admin_signed_in? %>
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
    <% else %>
      <%= link_to "ライターページ", new_writer_session_path %>
    <% end %>

app/views/layouts/_writers_header.html.erb
    <% if writer_signed_in? %>
      <%= link_to "ログアウト", destroy_writer_session_path, method: :delete %>
    <% else %>
      <%= link_to "ログイン", new_writer_session_path %>
      <span>/</span>
      <%= link_to "新規登録", new_writer_registration_path %>
      <span>/</span>
      <%= link_to "管理者ページ", new_admin_session_path %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Writerapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <div id="header-inner" class="clearfix">
        <div id="header-logo">Appロゴ</div>
        <div id="header-nav">
          <% if request.fullpath.match?(/^\/admins\/*/) %>
            <%= render "/layouts/admins_header" %>
          <% else %>
            <%= render "/layouts/writers_header" %>
          <% end %>
        </div>
      </div>
    </header>
    <div class="container">
      <div class="notificaiton">
        <% flash.each do |key, value| %>
          <%= content_tag(:p, value, class: "alert alert-#{key}") %>
        <% end %>
        <% if @article.present? && @article.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <ul>
              <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <%= yield %>
    </div>
    <footer>
      <p>Copyright © ysk management LLC All Rights Reserved.</p>
    </footer>
  </body>
</html>